// SPDX-License-Identifier: MIT OR Apache-2.0
//! RTL export (design §2.4): per-bank base LBA / slot shift / unit count
//! constants in Verilog header, SystemVerilog package, Rust, or C header form.

use crate::error::{Error, Result};
use crate::layout::Layout;
use crate::units::format_bytes;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RtlFormat {
    /// Verilog header (`localparam`), for `include`.
    Vh,
    /// SystemVerilog package.
    Sv,
    /// Rust constants.
    Rust,
    /// C header.
    CHeader,
}

impl std::str::FromStr for RtlFormat {
    type Err = Error;
    fn from_str(s: &str) -> Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "vh" => Ok(RtlFormat::Vh),
            "sv" => Ok(RtlFormat::Sv),
            "rs" | "rust" => Ok(RtlFormat::Rust),
            "h" | "c" => Ok(RtlFormat::CHeader),
            _ => Err(Error::Validation(format!(
                "unknown RTL format {s:?}: expected vh|sv|rs|h"
            ))),
        }
    }
}

impl RtlFormat {
    /// Infer from an output file extension.
    pub fn from_path(path: &std::path::Path) -> Option<RtlFormat> {
        match path.extension()?.to_str()? {
            "vh" | "v" => Some(RtlFormat::Vh),
            "sv" | "svh" => Some(RtlFormat::Sv),
            "rs" => Some(RtlFormat::Rust),
            "h" => Some(RtlFormat::CHeader),
            _ => None,
        }
    }
}

struct BankParams {
    prefix: String,
    comment: String,
    base_lba: u64,
    slot_shift: u32,
    units: u32,
    units_width: u32,
    /// Bit u set = slot u is POPULATED in the manifest (has an image).
    /// The RTL uses this as the drive-presence mask so a machine cannot
    /// advertise units the card does not carry — the same
    /// generated-not-vendored rule as the addressing constants.
    present: u64,
}

fn bank_params(layout: &Layout) -> Result<Vec<BankParams>> {
    let sector = u64::from(layout.sector_size);
    layout
        .banks
        .iter()
        .map(|b| {
            if !b.slot_size.is_power_of_two() {
                return Err(Error::Validation(format!(
                    "bank {:?}: slot_size {} is not a power of two; cannot export a SLOT_SHIFT",
                    b.name,
                    format_bytes(b.slot_size)
                )));
            }
            let slots_per = b.slot_size / sector;
            let type_note = match &b.drive_type {
                Some(t) => format!("{} x {}", t.name, b.units),
                None => format!("{} units", b.units),
            };
            let present = b
                .slots
                .values()
                .filter(|sl| sl.image.is_some() && sl.unit < b.units)
                .fold(0u64, |m, sl| m | (1u64 << sl.unit));
            Ok(BankParams {
                prefix: sanitize_upper(&b.name),
                comment: format!(
                    "Bank \"{}\": {type_note}, {} slots @ base {}",
                    b.name,
                    format_bytes(b.slot_size),
                    format_bytes(b.base)
                ),
                base_lba: b.base / sector,
                slot_shift: slots_per.trailing_zeros(),
                units: b.units,
                units_width: 32 - b.units.leading_zeros(),
                present,
            })
        })
        .collect()
}

fn sanitize_upper(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

/// Format a 32-bit hex constant with a `_` between the 16-bit halves,
/// matching hand-written Verilog style: `0010_0000`.
/// A `units`-wide binary literal, underscored every 4 bits from the LSB:
/// `0b0011_1111`. Bit u = slot u populated.
fn bin_mask(v: u64, units: u32) -> String {
    let bits: String = (0..units)
        .rev()
        .map(|i| if v >> i & 1 == 1 { '1' } else { '0' })
        .collect();
    let mut out = String::new();
    for (i, c) in bits.chars().enumerate() {
        if i > 0 && (bits.len() - i).is_multiple_of(4) {
            out.push('_');
        }
        out.push(c);
    }
    out
}

fn hex32(v: u64) -> String {
    format!("{:04x}_{:04x}", (v >> 16) & 0xffff, v & 0xffff)
}

pub fn export(layout: &Layout, format: RtlFormat, name: &str) -> Result<String> {
    let banks = bank_params(layout)?;
    let mut out = String::new();
    let push = |out: &mut String, s: &str| {
        out.push_str(s);
        out.push('\n');
    };
    let header = format!(
        "Generated by sdslot export-rtl; do not edit.\n\
         Sector size: {} bytes.",
        layout.sector_size
    );

    match format {
        RtlFormat::Vh | RtlFormat::Sv => {
            for line in header.lines() {
                push(&mut out, &format!("// {line}"));
            }
            push(&mut out, "");
            if format == RtlFormat::Sv {
                push(&mut out, &format!("package {};", sanitize_lower(name)));
                push(&mut out, "");
            }
            for b in &banks {
                push(&mut out, &format!("// {}", b.comment));
                push(
                    &mut out,
                    &format!(
                        "localparam {}_BASE_LBA   = 32'h{};",
                        b.prefix,
                        hex32(b.base_lba)
                    ),
                );
                push(
                    &mut out,
                    &format!("localparam {}_SLOT_SHIFT = {};", b.prefix, b.slot_shift),
                );
                push(
                    &mut out,
                    &format!(
                        "localparam {}_UNITS      = {}'d{};",
                        b.prefix, b.units_width, b.units
                    ),
                );
                push(
                    &mut out,
                    &format!(
                        "localparam {}_PRESENT    = {}'b{};",
                        b.prefix,
                        b.units,
                        bin_mask(b.present, b.units)
                    ),
                );
                push(&mut out, "");
            }
            if format == RtlFormat::Sv {
                push(&mut out, "endpackage");
            }
        }
        RtlFormat::Rust => {
            for line in header.lines() {
                push(&mut out, &format!("// {line}"));
            }
            push(&mut out, "");
            for b in &banks {
                push(&mut out, &format!("// {}", b.comment));
                push(
                    &mut out,
                    &format!(
                        "pub const {}_BASE_LBA: u32 = 0x{};",
                        b.prefix,
                        hex32(b.base_lba)
                    ),
                );
                push(
                    &mut out,
                    &format!("pub const {}_SLOT_SHIFT: u32 = {};", b.prefix, b.slot_shift),
                );
                push(
                    &mut out,
                    &format!("pub const {}_UNITS: u32 = {};", b.prefix, b.units),
                );
                push(
                    &mut out,
                    &format!(
                        "pub const {}_PRESENT: u32 = 0b{};",
                        b.prefix,
                        bin_mask(b.present, b.units)
                    ),
                );
                push(&mut out, "");
            }
        }
        RtlFormat::CHeader => {
            let guard = format!("{}_H", sanitize_upper(name));
            for line in header.lines() {
                push(&mut out, &format!("/* {line} */"));
            }
            push(&mut out, "");
            push(&mut out, &format!("#ifndef {guard}"));
            push(&mut out, &format!("#define {guard}"));
            push(&mut out, "");
            for b in &banks {
                push(&mut out, &format!("/* {} */", b.comment));
                push(
                    &mut out,
                    &format!("#define {}_BASE_LBA   0x{}u", b.prefix, hex32(b.base_lba)),
                );
                push(
                    &mut out,
                    &format!("#define {}_SLOT_SHIFT {}", b.prefix, b.slot_shift),
                );
                push(
                    &mut out,
                    &format!("#define {}_UNITS      {}", b.prefix, b.units),
                );
                push(
                    &mut out,
                    &format!("#define {}_PRESENT    0x{:x}u", b.prefix, b.present),
                );
                push(&mut out, "");
            }
            push(&mut out, &format!("#endif /* {guard} */"));
        }
    }
    Ok(out)
}

fn sanitize_lower(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn format_parses_from_strings_and_paths() {
        assert_eq!("vh".parse::<RtlFormat>().unwrap(), RtlFormat::Vh);
        assert_eq!("SV".parse::<RtlFormat>().unwrap(), RtlFormat::Sv);
        assert_eq!("rs".parse::<RtlFormat>().unwrap(), RtlFormat::Rust);
        assert_eq!("rust".parse::<RtlFormat>().unwrap(), RtlFormat::Rust);
        assert_eq!("h".parse::<RtlFormat>().unwrap(), RtlFormat::CHeader);
        assert_eq!("c".parse::<RtlFormat>().unwrap(), RtlFormat::CHeader);
        assert!("verilog".parse::<RtlFormat>().is_err());

        assert_eq!(RtlFormat::from_path(Path::new("x.vh")), Some(RtlFormat::Vh));
        assert_eq!(RtlFormat::from_path(Path::new("x.v")), Some(RtlFormat::Vh));
        assert_eq!(RtlFormat::from_path(Path::new("x.sv")), Some(RtlFormat::Sv));
        assert_eq!(
            RtlFormat::from_path(Path::new("x.svh")),
            Some(RtlFormat::Sv)
        );
        assert_eq!(
            RtlFormat::from_path(Path::new("x.rs")),
            Some(RtlFormat::Rust)
        );
        assert_eq!(
            RtlFormat::from_path(Path::new("x.h")),
            Some(RtlFormat::CHeader)
        );
        assert_eq!(RtlFormat::from_path(Path::new("x.txt")), None);
        assert_eq!(RtlFormat::from_path(Path::new("noext")), None);
    }

    #[test]
    fn present_mask_is_lsb_first_and_underscored() {
        // Bit u = slot u. The pdp11 card populates RP units 0..5 of 8,
        // so the RTL must read 8'b0011_1111 -- eight ADDRESSABLE units,
        // six drives installed. Getting the bit order backwards here
        // would silently advertise the wrong drives.
        assert_eq!(bin_mask(0b0011_1111, 8), "0011_1111");
        assert_eq!(bin_mask(0b0000_0001, 8), "0000_0001");
        assert_eq!(bin_mask(0b1000_0000, 8), "1000_0000");
        // 16-wide (the RL bank) and a non-multiple-of-4 width.
        assert_eq!(bin_mask(0b1, 16), "0000_0000_0000_0001");
        assert_eq!(bin_mask(0b101, 3), "101");
        // An empty bank is legal and must not panic.
        assert_eq!(bin_mask(0, 4), "0000");
    }

    #[test]
    fn identifiers_are_sanitized() {
        assert_eq!(sanitize_upper("9track-tape"), "_9TRACK_TAPE");
        assert_eq!(sanitize_lower("9Track Pkg"), "_9track_pkg");
        assert_eq!(hex32(0x40_0000), "0040_0000");
    }
}
